### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by Bishal44** [abhi5658/search-youtube#2]
/home/bishal/Desktop/androidstudio/BijayaDashamiTihar/app/src/main/java/com/bijayadashami/bishal/mainactivity.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

and 

Program type already present: javax.annotation.CheckForSigned
Message{kind=ERROR, text=Program type already present: javax.annotation.CheckForSigned, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by dhakadmahesh** [comment]
at com.media.hd.videos.player.MainActivity$2.onQueryTextChange(MainActivity.java:161)

i have error in this project on search app stopped

also error in youtubeAdapter.class in 

@Override
public int getItemCount() {
        return mVideoList.size();
 }
